name: 🐛 Bug Report
description: Report a bug or unexpected behavior in the Reisinger IntelliApp
title: "[BUG] "
labels: ["bug", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible to help us resolve the issue.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened.
      placeholder: What actually happened?
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: Which platform(s) are you experiencing this issue on?
      multiple: true
      options:
        - Android
        - iOS
        - Windows
        - macOS
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: App Version
      description: What version of the app are you using?
      placeholder: "e.g., 1.0.0"
    validations:
      required: true

  - type: textarea
    id: device_info
    attributes:
      label: Device Information
      description: Device and OS information
      placeholder: |
        - Device: [e.g., iPhone 14, Samsung Galaxy S23, Windows 11 PC]
        - OS Version: [e.g., iOS 16.5, Android 13, Windows 11]
        - .NET Version: [e.g., .NET 9.0]
      render: markdown

  - type: textarea
    id: logs
    attributes:
      label: Error Logs/Screenshots
      description: If applicable, add error logs or screenshots to help explain your problem.
      placeholder: Paste error logs or drag and drop screenshots here...

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
      placeholder: Any additional information that might be helpful...

  - type: checkboxes
    id: copilot_related
    attributes:
      label: Copilot-Related
      description: Is this issue related to GitHub Copilot suggestions or generated code?
      options:
        - label: This issue is related to GitHub Copilot generated code
        - label: This issue was encountered while using Copilot suggestions
        - label: This issue affects Copilot's ability to provide suggestions

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our code of conduct.
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true