name: ✨ Feature Request
description: Suggest a new feature or enhancement for the Reisinger IntelliApp
title: "[FEATURE] "
labels: ["enhancement", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible to help us understand your request.

  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: A brief summary of the feature you'd like to see added.
      placeholder: Briefly describe the feature...
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What's the current limitation?
      placeholder: |
        Currently, users cannot...
        This would help with...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented.
      placeholder: |
        I would like to see...
        This could be implemented by...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Describe any alternative solutions or features you've considered.
      placeholder: |
        Alternatively, we could...
        Other options might include...

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve workflow
        - High - Critical for my use case
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: Target Platform(s)
      description: Which platform(s) should this feature target?
      multiple: true
      options:
        - Android
        - iOS
        - Windows
        - macOS
        - All platforms
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What category does this feature fall into?
      options:
        - Device Control
        - User Interface
        - Connectivity
        - Settings/Configuration
        - Performance
        - Security
        - Accessibility
        - Developer Experience
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: use_cases
    attributes:
      label: Use Cases
      description: Describe specific use cases or scenarios where this feature would be helpful.
      placeholder: |
        - Use case 1: When...
        - Use case 2: If...
        - Use case 3: During...

  - type: textarea
    id: mockups
    attributes:
      label: Mockups/Screenshots
      description: If applicable, add mockups, wireframes, or reference screenshots.
      placeholder: Drag and drop images here or describe the UI...

  - type: checkboxes
    id: copilot_integration
    attributes:
      label: Copilot Integration
      description: Should this feature integrate with GitHub Copilot?
      options:
        - label: This feature should leverage GitHub Copilot for code generation
        - label: This feature should provide better context for Copilot suggestions
        - label: This feature requires Copilot-specific documentation

  - type: textarea
    id: technical_considerations
    attributes:
      label: Technical Considerations
      description: Any technical considerations, dependencies, or constraints for this feature?
      placeholder: |
        - Dependencies: ...
        - Constraints: ...
        - Integration points: ...

  - type: checkboxes
    id: volunteer
    attributes:
      label: Implementation
      description: Are you willing to help implement this feature?
      options:
        - label: I'm willing to submit a pull request for this feature
        - label: I can help with testing this feature
        - label: I can help with documentation for this feature

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our code of conduct.
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true